# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-10 05:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Harshi', max_length=50)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50, null=True)),
                ('area', models.CharField(default='Mylapore', max_length=100)),
                ('house_number', models.IntegerField(default=1)),
                ('street_name', models.CharField(default='1st Main Road', max_length=50)),
                ('Landmark', models.CharField(default='Near Billroth Hospital', max_length=50)),
                ('Pincode', models.IntegerField(default=600028)),
                ('State', models.CharField(default='TN', max_length=50)),
                ('contact', models.IntegerField()),
            ],
            options={
                'db_table': 'Customer',
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(default='/static/food_gawker.jpg/', upload_to='Desktop/')),
                ('name', models.CharField(default='Drunken Monkey', max_length=50)),
                ('area', models.CharField(default='Alwarpet', max_length=50)),
                ('address', models.TextField(default='address', max_length=100)),
                ('phone', models.IntegerField(default=1233)),
                ('approximate_cost', models.IntegerField(default=350)),
                ('special_food', models.CharField(default='Willi Wonka', max_length=50)),
                ('rating', models.CharField(default='Rate', max_length=5)),
                ('review', models.TextField(default='Good', max_length=100)),
                ('food_name', models.CharField(default='Enter Food Name', max_length=50)),
                ('food_description', models.TextField(default='Enter description', max_length=500)),
                ('food_image', models.ImageField(default='/static/food_gawker.jpg/', upload_to='Desktop/')),
                ('min_time', models.CharField(default='20 mins', max_length=50)),
                ('food_cost', models.IntegerField(default=50)),
                ('food_rate', models.CharField(default='Rate', max_length=5)),
            ],
            options={
                'db_table': 'Hotel',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.IntegerField()),
                ('hotel_name', models.CharField(max_length=100)),
                ('food_name', models.CharField(max_length=100)),
                ('review', models.CharField(max_length=200)),
                ('complaints', models.CharField(default='Enter Your complaints Here', max_length=100)),
                ('Rate_us', models.CharField(default='*****', max_length=5)),
            ],
            options={
                'db_table': 'Review',
            },
        ),
    ]
