# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-10 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(default='Enter Food Name', max_length=50)),
                ('food_description', models.TextField(default='Enter description', max_length=500)),
                ('food_image', models.ImageField(default='/static/food_gawker.jpg/', upload_to='Desktop/')),
                ('min_time', models.CharField(default='20 mins', max_length=50)),
                ('food_cost', models.IntegerField(default=50)),
                ('food_rate', models.CharField(default='Rate', max_length=5)),
            ],
            options={
                'db_table': 'Food',
            },
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='food_cost',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='food_description',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='food_image',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='food_name',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='food_rate',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='min_time',
        ),
    ]
