# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-26 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='name',
            field=models.CharField(default='harshi', max_length=50),
        ),
    ]
