# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-26 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='set_password',
            field=models.CharField(default='harshi08', max_length=10),
        ),
        migrations.AddField(
            model_name='customer',
            name='set_username',
            field=models.CharField(default='harshi@example.com', max_length=50),
        ),
    ]
