# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-10 09:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_auto_20190110_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='food_name',
            field=models.ForeignKey(default='Enter Food Name', max_length=50, on_delete=django.db.models.deletion.CASCADE, to='foods.Hotel'),
        ),
    ]
