# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-26 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_auto_20181226_1511'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='is_customer',
            new_name='cuisine',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='cuisine',
        ),
        migrations.AddField(
            model_name='customer',
            name='remember',
            field=models.BooleanField(choices=[('V', 'Veg'), ('NV', 'NonVeg')], default=True),
        ),
    ]
