# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-10 09:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_auto_20190110_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='food_cost',
        ),
        migrations.RemoveField(
            model_name='food',
            name='food_rate',
        ),
        migrations.RemoveField(
            model_name='review',
            name='complaints',
        ),
        migrations.RemoveField(
            model_name='review',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='review',
            name='food_name',
        ),
        migrations.RemoveField(
            model_name='review',
            name='hotel_name',
        ),
        migrations.RemoveField(
            model_name='review',
            name='review',
        ),
        migrations.AlterField(
            model_name='food',
            name='food_description',
            field=models.CharField(default='Enter description', max_length=500),
        ),
        migrations.AlterField(
            model_name='food',
            name='food_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foods.Hotel'),
        ),
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foods.Customer'),
        ),
    ]
