# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-11 04:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0004_auto_20190110_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='food_name',
        ),
        migrations.RemoveField(
            model_name='review',
            name='name',
        ),
        migrations.DeleteModel(
            name='Food',
        ),
        migrations.DeleteModel(
            name='Hotel',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
