# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-11 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0005_auto_20190111_0959'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(default='/static/food_gawker.jpg/', upload_to='Desktop/')),
                ('name', models.CharField(default='Drunken Monkey', max_length=50)),
                ('area', models.CharField(default='Alwarpet', max_length=50)),
                ('address', models.TextField(default='address', max_length=100)),
                ('phone', models.IntegerField(default=1233)),
                ('approximate_cost', models.IntegerField(default=350)),
                ('special_food', models.CharField(default='Willi Wonka', max_length=50)),
                ('rating', models.CharField(default='Rate', max_length=5)),
                ('review', models.TextField(default='Good', max_length=100)),
            ],
            options={
                'db_table': 'Hotel',
            },
        ),
    ]
