# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-26 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0006_remove_customer_cuisine'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cuisine',
            field=models.CharField(default='Veg', max_length=20),
        ),
    ]
