# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-11 04:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0007_food'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rate_us', models.CharField(default='*****', max_length=5)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foods.Customer')),
            ],
            options={
                'db_table': 'Review',
            },
        ),
    ]
