# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-11 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0008_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cuisine',
            field=models.CharField(choices=[('V', 'Veg'), ('NV', 'NonVeg')], default='Veg', max_length=1),
        ),
    ]
