# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-27 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0008_auto_20181227_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='delivery_time',
            field=models.CharField(default='2 mins', max_length=10),
        ),
        migrations.AddField(
            model_name='hotel',
            name='max_num',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='customer',
            name='username',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='food_rate',
            field=models.CharField(default='**', max_length=5),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotel_rate',
            field=models.CharField(default='**', max_length=5),
        ),
    ]
