# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-27 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0009_auto_20181227_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='delivery_time',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='hotel_rate',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='max_num',
        ),
        migrations.AddField(
            model_name='hotel',
            name='address',
            field=models.TextField(default='address', max_length=100),
        ),
        migrations.AddField(
            model_name='hotel',
            name='approximate_cost',
            field=models.IntegerField(default=350),
        ),
        migrations.AddField(
            model_name='hotel',
            name='food_description',
            field=models.TextField(default='Enter description', max_length=500),
        ),
        migrations.AddField(
            model_name='hotel',
            name='min_time',
            field=models.CharField(default='20 mins', max_length=50),
        ),
        migrations.AddField(
            model_name='hotel',
            name='phone',
            field=models.IntegerField(default=1233),
        ),
        migrations.AddField(
            model_name='hotel',
            name='rating',
            field=models.CharField(default='Rate', max_length=5),
        ),
        migrations.AddField(
            model_name='hotel',
            name='review',
            field=models.TextField(default='Good', max_length=100),
        ),
        migrations.AddField(
            model_name='hotel',
            name='special_food',
            field=models.CharField(default='Willi Wonka', max_length=50),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='area',
            field=models.CharField(default='Alwarpet', max_length=50),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='food_cost',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='food_name',
            field=models.CharField(default='Enter Food Name', max_length=50),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='food_rate',
            field=models.CharField(default='Rate', max_length=5),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='name',
            field=models.CharField(default='Drunken Monkey', max_length=50),
        ),
    ]
