# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-14 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0009_customer_cuisine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='cuisine',
        ),
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(default='Harshi', max_length=20),
        ),
    ]
