# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-27 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0010_auto_20181227_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='address',
        ),
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.CharField(max_length=200),
        ),
    ]
