# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-14 08:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0010_auto_20190114_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foods.Customer'),
        ),
    ]
