# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-14 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0011_auto_20190114_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='contact',
            field=models.IntegerField(null=True),
        ),
    ]
