# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-14 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0012_auto_20190114_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(default='Harshi', max_length=20),
        ),
    ]
