# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-31 09:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0014_remove_customer_cuisine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='remember',
        ),
    ]
