# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-02 05:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0015_remove_customer_remember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(default='Harshi', max_length=50),
        ),
    ]
