# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-14 11:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0015_hotel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_description', models.CharField(default='Enter description', max_length=500)),
                ('food_image', models.ImageField(default='/static/food_gawker.jpg/', upload_to='Desktop/')),
                ('min_time', models.CharField(default='20 mins', max_length=50)),
                ('cost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_cost', to='foods.Hotel')),
                ('food_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foods.Hotel')),
                ('rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_rate', to='foods.Hotel')),
            ],
            options={
                'db_table': 'Food',
            },
        ),
    ]
