# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-14 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0016_food'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Harshi', max_length=20)),
                ('Rate_us', models.CharField(default='*****', max_length=5)),
            ],
            options={
                'db_table': 'Review',
            },
        ),
    ]
