# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-02 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0016_auto_20190102_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(default=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='set_password',
            field=models.CharField(default=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='set_username',
            field=models.CharField(default=True, max_length=50),
        ),
    ]
