# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-03 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0017_auto_20190102_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(default='Harshi', max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='set_password',
            field=models.CharField(default='harshi1308', max_length=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='set_username',
            field=models.CharField(default='harshi@example.com', max_length=50),
        ),
    ]
