# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-03 05:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0018_auto_20190103_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='food_image',
            field=models.ImageField(default='/static/food_gawker.jpg/', upload_to='Desktop/'),
        ),
    ]
