# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-03 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0019_hotel_food_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='logo',
            field=models.ImageField(default='/static/food_gawker.jpg/', upload_to='Desktop/'),
        ),
    ]
