# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-03 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0020_hotel_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='area',
            field=models.CharField(default='Mylapore', max_length=100),
        ),
    ]
