# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-04 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0021_auto_20190103_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='Rate_us',
            field=models.CharField(default='*****', max_length=5),
        ),
    ]
