# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-28 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0022_auto_20190128_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='username',
            field=models.CharField(default='Enter either username or contact', max_length=20),
        ),
    ]
