# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-28 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0023_auto_20190128_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='username',
            field=models.CharField(default='Enter either username or registered phone number', max_length=20),
        ),
    ]
