# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-29 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0024_auto_20190128_1201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='food_description',
            new_name='Hotel_description',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='food_image',
            new_name='Hotel_image',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='food_name',
            new_name='Hotel_name',
        ),
        migrations.RemoveField(
            model_name='food',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='review',
        ),
        migrations.RemoveField(
            model_name='review',
            name='Rate_us',
        ),
        migrations.AddField(
            model_name='review',
            name='Hotel_rating',
            field=models.CharField(default='Rate', max_length=5),
        ),
        migrations.AddField(
            model_name='review',
            name='Hotel_review',
            field=models.TextField(default='Good', max_length=100),
        ),
    ]
