# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-29 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0025_auto_20190129_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='Hotel_review',
            field=models.CharField(default='Good', max_length=100),
        ),
    ]
