# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-30 09:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0027_auto_20190130_1505'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='hotel_description',
            new_name='Hotel_description',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='hotel_name',
            new_name='Hotel_name',
        ),
        migrations.RemoveField(
            model_name='food',
            name='hotel_image',
        ),
    ]
