# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-30 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0029_customer_confirm_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='username',
            field=models.CharField(default='Enter username or registered phone number', max_length=20),
        ),
    ]
