# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-07 06:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0030_auto_20190130_1636'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='Hotel_description',
            new_name='hotel_description',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='Hotel_name',
            new_name='hotel_name',
        ),
    ]
