# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-07 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0031_auto_20190207_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='rate',
            field=models.CharField(default='*****', max_length=5),
        ),
    ]
