# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-07 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0032_food_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='image',
            field=models.ImageField(default='ss/page12_signout.PNG', upload_to='media'),
        ),
    ]
